S of S.O.L.I.D principle satisfied
Muhammadali2025222/C-Practice pull request #14
Opened 2024-11-20 13:01 UTC by Muhammadali2025222

Added comments and created a class that now handles inheritance from abstract classes and changes in child classes, main and shapefactory are made

2024-11-20 16:00 UTC, abbasshah17 commented
1. Change your comments to: "This class follows the Single Responsibility Principle.
2. Mention the responsibility of the class as you understand it.

2024-11-23 20:54 UTC, abbasshah17 commented
Still missing the description of the responsibility of each class in the comments.

Before deciding whether or not a class is following the Single Responsibility principle, first you need to understand the responsibility of the class or define it.

Once you've defined the responsibility of the class you can then assess whether or not the class follows the single responsibility principle or not.

2024-11-23 20:55 UTC, abbasshah17 requested changes
Still missing the description of the responsibility of each class in the comments.

Before deciding whether or not a class is following the Single Responsibility principle, first you need to understand the responsibility of the class or define it.

Once you've defined the responsibility of the class you can then assess whether or not the class follows the single responsibility principle or not.

2024-11-25 12:58 UTC, Muhammadali2025222 commented
I have suggestion that we create separate classes to override these methods.
For example
FOR CIRCLE: a circle drawer class a circle input class and then a circle volume and a circle area.
FOR RECTANGLE: a Rectangle drawer class a Rectangle input class and then a Rectangle volume and a Rectangle area.
FOR SQUARE: a Square drawer class a Square input class and then a Square volume and a Square area.
FOR TRIANGLE: a Triangle drawer class a Triangle input class and then a Triangle volume and a Triangle area.

2024-11-25 13:14 UTC, abbasshah17 commented on Circle.cpp
> +//Responsibility: This class is responsible to provide implementation for draw(), inputDimensions, calculateArea(), and calculateVolume().
You cannot use function names as the class's responsiblity. This is like defining a meaning of a word using the same word.

You need to focus on what drives the class's existence / creation or in other words what purpose the class is to fulfil.

The next step comes after: i.e. the purpose of the class should be single.

Once you've identified how the class violates that single responsibility principle, you need to state how it does so.

2024-11-25 13:17 UTC, abbasshah17 commented on Enum.cpp
> +Shapes fromStringtoEnum(string shapeType)   // The function fromStringtoEnum() follows Single responsibility principle.
We're currently discussing single responsibility principle for a class. The SOLID principle do not deal with low level implementations such as functions (even though it is a good practice to ensure that a function serves one purpose or job), this function's single responsibility is out of the scope of this task.

2024-11-25 13:18 UTC, abbasshah17 commented on Input.cpp
> +class Input  //Responsibility: This class provides a common interface for taking input.
Should be updated to

    //Responsibility: This class provides a common interface for taking input from user.

OR

    //Responsibility: This class provides a common interface for taking user-input.

2024-11-25 13:20 UTC, abbasshah17 commented on Main.cpp
> +    ShapeManager *shapeHandler = ShapeFactory ::create(shapeType);
Code refactoring was not part of this task. This PR should solely focus on identifying the responsibility of the classes.

2024-11-25 13:20 UTC, abbasshah17 commented on Rectangle.cpp
> +class Rectangle : public ShapeManager
See above [comment](https://github.com/Muhammadali2025222/C-Practice/pull/14/files#r1856597527).

2024-11-25 13:23 UTC, abbasshah17 commented on ShapeManager.cpp
> +// This class follows the Single Responsibility Principle.
The name / description of the responsibility of the class do not match.

The class name suggests, it *manages* `Shape`s. However, from the code, we can see that `ShapeManager` is a `Shape` itself.

2024-11-25 13:23 UTC, abbasshah17 commented on Square.cpp
> +//Responsibility: This class is responsible to provide implementation for draw(), inputDimensions, calculateArea(), and calculateVolume().
Same as before, check [comment](https://github.com/Muhammadali2025222/C-Practice/pull/14/files#r1856597527)

2024-11-25 13:24 UTC, abbasshah17 commented on Triangle.cpp
> +//Responsibility: This class is responsible to provide implementation for draw(), inputDimensions, calculateArea(), and calculateVolume().
Same as before, see [comment](https://github.com/Muhammadali2025222/C-Practice/pull/14/files#r1856597527).

2024-11-25 13:30 UTC, abbasshah17 requested changes
See [comment](https://github.com/Muhammadali2025222/C-Practice/pull/14/files#r1856597527)

You are still failing to understand what a class's responsibilities are and how to define them. 

Try this approach, without any code changes (such as `ShapeManager`):

1. Go through each class one by one, analyze how it interacts with other classes.
2. Analyze the current exposed contracts the class provides.
3. Write the responsibility of each class.
4. Again, one by one go to each class and determine whether the responsibility is singular in nature.
5. And then give your verdict of whether a class violates or follows the Single Responsibility principle.

In order to simplify this process. For now, focus on merely identifying the responsibilities of each class instead of focusing on whether it satisfies the Single Responsibility principle. That is, only go through points 1 - 3 mentioned above.

2024-11-28 09:52 UTC, abbasshah17 approved these changes

2024-11-28 09:57 UTC, merged